{{/*
PodTemplate
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-template-v1/
*/}}
{{- define "generic.resources.inc.podTemplate" -}}

{{- $podTemplate := .generic.podTemplate -}}
{{- include "generic.useTemplates" (dict "helm" .helm "resource" $podTemplate) -}}

template:
  metadata:
    {{- with $podTemplate.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    labels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  spec:
    containers:
      {{- $_ := set .generic "containersList" $podTemplate.containers }}
      {{- include "generic.resources.inc.containersList" . | nindent 6 }}
      {{- $_ := unset .generic "containersList" }}
    {{- if $podTemplate.initContainers }}
    initContainers:
      {{- $_ := set .generic "containersList" $podTemplate.initContainers }}
      {{- include "generic.resources.inc.containersList" . | nindent 6 }}
      {{- $_ := unset .generic "containersList" }}
    {{- end }}

    {{- if $podTemplate.volumes }}
    volumes:
      {{- range $volume := $podTemplate.volumes -}}
        {{/*- $volume := deepCopy $volume */}}
        {{- if kindIs "map" ($volume.persistentVolumeClaim).claimName }}
          {{- $_ := set $volume.persistentVolumeClaim "claimName" (include "generic.fullResourceName" (dict
            "helm" $.helm
            "generic" (dict
              "componentName" (default $.generic.componentName $volume.persistentVolumeClaim.claimName.componentName)
              "resourceName"  (default $.generic.resourceName $volume.persistentVolumeClaim.claimName.resourceName)
            )
          )) }}
        {{- end }}
        {{- if kindIs "map" ($volume.configMap).name }}
          {{- $_ := set $volume.configMap "name" (include "generic.fullResourceName" (dict
            "helm" $.helm
            "generic" (dict
              "componentName" (default $.generic.componentName $volume.configMap.name.componentName)
              "resourceName"  (default $.generic.resourceName $volume.configMap.name.resourceName)
            )
          )) }}
        {{- end }}
        {{- if kindIs "map" ($volume.secret).secretName }}
          {{- $_ := set $volume.secret "secretName" (include "generic.fullResourceName" (dict
            "helm" $.helm
            "generic" (dict
              "componentName" (default $.generic.componentName $volume.secret.secretName.componentName)
              "resourceName"  (default $.generic.resourceName $volume.secret.secretName.resourceName)
            )
          )) }}
        {{- end }}
        {{- toYaml (list $volume) | nindent 6 }}
      {{- end }}
    {{- end }}

    {{- with $podTemplate.rawSpec }}{{ toYaml . | nindent 4 }}{{ end }}

{{- end }}
