{{- range $componentName, $component := .Values.components }}
{{- if or $component.enabled (not (hasKey $component "enabled")) }}

{{- if $component.resources }}
{{- range $resourceName, $resource := $component.resources }}
{{- if or $resource.enabled (not (hasKey $resource "enabled")) }}

{{/*- $resource := deepCopy $resource */}}
{{- include "generic.useTemplates" (dict "helm" $ "resource" $resource) }}

{{- include (print "generic.resources." $resource.type) (dict
  "helm" $
  "generic" (dict
    "componentName" $componentName
    "component" $component
    "resourceName" $resourceName
    "resource" $resource
  )
) }}

{{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
