{{- $_ := set . "generic" (dict "ctx" (dict) "callStack" (list)) }}
{{- range $dummyComponentName, $component := .Values.components }}
  {{/* $component := deepCopy $component */}}
  {{- $_ := set $.generic.ctx "componentName" $component.componentName }}
  {{- $_ := set $.generic "callStack" (prepend $.generic.callStack (dict
    "obj" $component
  )) }}
  {{- if and ($component.resources) (not (include "generic.isDisabled" $)) }}
    {{- range $dummyResourceName, $resource := $component.resources }}
      {{/* $resource := deepCopy $resource */}}
      {{- $_ := set $.generic.ctx "resourceName" $resource.resourceName }}
      {{- $_ := set $.generic "callStack" (prepend $.generic.callStack (dict
        "obj" $resource
      )) }}
      {{- if and (not (include "generic.isDisabled" $)) $resource.manifest }}
        {{/* $manifest := deepCopy $resource.manifest */}}
        {{- $manifest := $resource.manifest }}
        {{- $_ := set $.generic "callStack" (prepend $.generic.callStack (dict
          "obj" $manifest
        )) }}
        {{- include "generic.processKeys" $ }}

---
{{ $manifest | toYaml }}

        {{- $_ := set $.generic "callStack" (rest $.generic.callStack) }}
      {{- end }}
      {{- $_ := unset $.generic.ctx "resourceName" }}
      {{- $_ := set $.generic "callStack" (rest $.generic.callStack) }}
    {{- end }}
  {{- end }}
  {{- $_ := unset $.generic.ctx "componentName" }}
  {{- $_ := set $.generic "callStack" (rest $.generic.callStack) }}
{{- end }}
