{{/*
Deployment
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
*/}}
{{- define "generic.resources.deployment" -}}

{{- $deployment := .generic.resource }}
{{- $_ := set .generic "podTemplate" $deployment.podTemplate }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullResourceName" . }}
  {{- with $deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "generic.resourceLabels" . | nindent 4 }}
spec:
  replicas: {{ $deployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}

  {{- include "generic.resources.inc.podTemplate" . | nindent 2 }}

  {{- with $deployment.rawSpec }}{{ toYaml . | nindent 2 }}{{ end }}

{{- $_ := unset .generic "podTemplate" }}

{{- end }}
