{{/*
Raw Manifest
https://kubernetes.io/docs/reference/kubernetes-api/
*/}}
{{- define "generic.resources.raw" -}}

{{- $manifest := default (dict) .generic.resource.manifest }}
{{- $metadata := default (dict) $manifest.metadata }}
{{- $labels := default (dict) $metadata.labels }}

{{- if not $metadata.name }}
{{- $_ := set $metadata "name" (include "generic.fullResourceName" .) }}
{{- end }}

{{- $labels := merge $labels (fromYaml (include "generic.resourceLabels" .)) }}

{{- $_ := set $metadata "labels" $labels }}
{{- $_ := set $manifest "metadata" $metadata }}

---
{{- toYaml $manifest }}

{{- end }}
